#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_PYTHON_DIR/virtenv/bin/activate

# If no database exists create one with sample content.
#if [ ! -f $OPENSHIFT_DATA_DIR/sqlite3.db ]
#then
#    echo "Creating intial database with example content."
#    python "$OPENSHIFT_REPO_DIR"wsgi/manage.py createdb --noinput --settings=settings.production
#fi

# Always collect static files, static dir is erased on push and we might have
# something new.
echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/manage.py collectstatic --noinput

#python "$OPENSHIFT_REPO_DIR"wsgi/manage.py createdb --noinput --settings=settings.production

#python "$OPENSHIFT_REPO_DIR"wsgi/manage.py migrate --noinput --settings=settings.production


# Make the web root files (favicon.ico, robots.txt) available 

ln -sf $OPENSHIFT_REPO_DIR/wsgi/wwwroot $OPENSHIFT_DATA_DIR/static/wwwroot

# Override Mezzanine default icon
cp -rf $OPENSHIFT_REPO_DIR/wsgi/wwwroot/favicon.ico $OPENSHIFT_DATA_DIR/static/img/favicon.ico
