language: python
sudo: false
python:
  - "3.3"
install:
  - pip install -r requirements.txt
before_script:
    # - flake8 .
    - python manage.py migrate
script:
    - python manage.py test
after_success:
    # - coveralls
notifications:
    email: false
