language: python
python:
- '3.3'
cache: pip
env:
  global:
  - DEBUG=False
  - secure: "Ldw7N0iWbPAF2JIfFzkGhnVTUBNKOT3aEwMIwE/10mjchAcCdNaVekjxVzwe8Dl3qbBhE+XImGXWTXjBXpopQMBprj9ELSqiI
        hzEsXtHtnioyPyMvsrgLdcEH1n1UrhGthiNXST54sDcLrufAU4VtjQiEZKKh/FGZEHlTbyc719e24nbMsl62IjcWiHYsENzwsBMjiMuH0M6+
        dWNVvaRcJf3AFKy9o6JbUvuxevWx7AoDMTvnm4FVZ5iGDOSuAtdzPaxODCyGWush88y0ybMd1gwdfSOSENg0E1cWZPKKYMx3fwhyUgV1iKB8
        4GCSJiGsjk9HkldH/X9vjP0cDZ/0xhRPly9+Ak/YfOKTdor7NF6fXAFqeH/1yNXUIHy8e8Sq5vx7Hi0M91liawZQNU2Mkr4hXnUj9v/BZuQ+
        q5/V1XvM1WRwcQfguKHEWsutdlgIb0zgJkN183dkIIFEz/IfBkYXnJIwzYqWVdBsZE7UXs9xRw/k1SWlbn3/dwcr79jYDsqtAxClx8jPUJ9A
        Pcf9sBnQ/mT6hlt9IadxQXlpm6/H/Ts//r0fT9oGE8GbBfnNFMELmezyEbvc2ik3I4ZGJS+6fAK+Bnz2OZdqgQuwcmfgD71nywT/jUjY3ZkH
        /du83RbQzulz/rzUDgGk/fDzL3O982wPkOxniH4awV3UxY="
  - DATABASE_URL=psql://postgres:@127.0.0.1:5432/ahabook
  - ALLOWED_HOSTS=127.0.0.1,localhost,0.0.0.0
  - secure: prqAzWnY+Ue5cIlqisVAkUkBZN8d+L4JyXEz8qBZSCuMMKBUgm2cj6zX+pOHeVrbuOcaIxikdolT8Vfy6x8B941g09UVpulEB
      E192IjtYLXpOJhRezwWX2E+R1yg/95KTXWHUrZDxfs47bjqnHsAjY/2fZJ3UoSy/nWhgeYu7aLmxM0S1bCUe+ee/JLZaY5tlwct9cqXu+Lsl
      L4oNXVDVP4dJxa5mV1SKSfbsGmTv0bFP8P1ZZVJ0Z+BM+k+VSdJ5Y7ThieoPAAzKhL6QmtbkOcxC2KeZXpjeHHbCXOvLc46iezEV60YlkSYx
      nWrG5/5vEtvhP2cXFV7FiS9cIDArWKAKTN4ZdgFEHVP+rjQs0ST8wBEIK/e9QT0tgGu8szQSDzt6FCFyrDMdFlAddOwok5XYYZZoAokC/QiQ
      WsqO3Bh86BCbWdsV0Xnsn6Sb9iw8G/f3EGF1w5+6FkPxa6NYfm1KRBa3jVmggbM6CfMS02nyOwQI2TKGxLcM1l73IB6tXQffk8NAvJn/d6nN
      OAQVQvUG3KIvCfW2jwILYLy/g7xqUUD+5e3oBcz7l+aceAg1ON/CZYbzqWiilcLagHOOjK1m2eJXT39Uyu/CW7YdYaUK6gW+DKieipe9aro3
      Nx1AePSm6HZpC/8msYgGVwn0tk/mH2FONc20J2f6Y5dwAY=
addons:
  postgresql: '9.2'
services:
- postgresql
install:
- pip install -r requirements/test.txt
before_script:
- psql -c 'create database ahabook;' -U postgres
- python manage.py migrate --settings=settings.production
script:
- python manage.py test --settings=settings.production
after_success: 
notifications:
  email: false

