language: python
python:
- '3.3'
cache: pip
env:
  global:
  - DEBUG=False
  - secure: AB+PK3oqmbWtERt9RahyFzIwG0nQMAOzF/fNQPDTHee/Bt6sod0hBp6L8zCqt7PodPKKlsuxsz1+kAQ/4racgLAa1LhOh5J+/KkQA66AMMNdKhUHa8ll21q1GKzTx2fp6R+2ngSmVWAY22sYuZYLfeRMeaYO7OOK3VM5rt+CcWQTSItrC1S3n9rJDX6vdFRqqklI0ODvt9CzkahnFc0a0a7C5xMMvv9MCaydbh+rGombq3wErylDjMItNhEi9gIIIoCPkuOUUW8AVN2FoDQS0dWb1WeEHdEtZX0ataXmB7fEepq9l1gU1bXPe4/sQ5sHv8mj8xF37aK2P8Yh3RIJmyVm6NJ2tonRwP6jXuCYDy9MtNYdvAR2YpIRiQ/l/oEH3AbZR24C1GMadVzpYkFBhvz85fWjcckAENsi8zWt+8+FRa/mHHbhEoumqtVYcebl6tjVBB3bQ6agLztwMpj6AiDUkmOEV3Ti7W/+HQF49Np2/NRgjh0tfk1QiPBFKmKJGX/ayO/IDMRIPAHzmdrLYH+b+cnYAGUuMOvOmx/maGPfDagzkGyBA7N3Oblszn3+4vqkMZ73RAgyTG4elKZGL600OJghimaK00gUsIJV0hzd+4xQqdbPYGFhEp7Ii27WfATX92dlpUNKOAsGiqxUjtqBVHHYNWxRTcDcmVZcE3k=
  - DATABASE_URL=psql://postgres:@127.0.0.1:5432/ahabook
  - ALLOWED_HOSTS=127.0.0.1,localhost,0.0.0.0
  - secure: prqAzWnY+Ue5cIlqisVAkUkBZN8d+L4JyXEz8qBZSCuMMKBUgm2cj6zX+pOHeVrbuOcaIxikdolT8Vfy6x8B941g09UVpulEB
      E192IjtYLXpOJhRezwWX2E+R1yg/95KTXWHUrZDxfs47bjqnHsAjY/2fZJ3UoSy/nWhgeYu7aLmxM0S1bCUe+ee/JLZaY5tlwct9cqXu+Lsl
      L4oNXVDVP4dJxa5mV1SKSfbsGmTv0bFP8P1ZZVJ0Z+BM+k+VSdJ5Y7ThieoPAAzKhL6QmtbkOcxC2KeZXpjeHHbCXOvLc46iezEV60YlkSYx
      nWrG5/5vEtvhP2cXFV7FiS9cIDArWKAKTN4ZdgFEHVP+rjQs0ST8wBEIK/e9QT0tgGu8szQSDzt6FCFyrDMdFlAddOwok5XYYZZoAokC/QiQ
      WsqO3Bh86BCbWdsV0Xnsn6Sb9iw8G/f3EGF1w5+6FkPxa6NYfm1KRBa3jVmggbM6CfMS02nyOwQI2TKGxLcM1l73IB6tXQffk8NAvJn/d6nN
      OAQVQvUG3KIvCfW2jwILYLy/g7xqUUD+5e3oBcz7l+aceAg1ON/CZYbzqWiilcLagHOOjK1m2eJXT39Uyu/CW7YdYaUK6gW+DKieipe9aro3
      Nx1AePSm6HZpC/8msYgGVwn0tk/mH2FONc20J2f6Y5dwAY=
addons:
  postgresql: '9.2'
services:
- postgresql
install:
- pip install -r requirements/test.txt
before_script:
- psql -c 'create database ahabook;' -U postgres
- python manage.py migrate --settings=settings.production
script:
- python manage.py test --settings=settings.production
after_success: 
notifications:
  email: false

